@php($other = is_array($employee->other_information) ? $employee->other_information : json_decode($employee->other_information, true))
@php($salaryInfo = data_get($other, 'salary_info', []))
<div class="row">
    <div class="col-md-6 mb-2"><label class="mb-1">Gross Salary(Actual)</label><input type="number" step="0.01" name="gross_salary" value="{{ old('gross_salary', $employee->gross_salary) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Gross Salary(Comp-01)</label><input type="number" step="0.01" name="gross_salary_comp_1" value="{{ old('gross_salary_comp_1', data_get($salaryInfo, 'gross_salary_comp_1')) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Gross Salary(Comp-02)</label><input type="number" step="0.01" name="gross_salary_comp_2" value="{{ old('gross_salary_comp_2', data_get($salaryInfo, 'gross_salary_comp_2')) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Payment Mode</label><input type="text" name="salary_type" value="{{ old('salary_type', $employee->salary_type) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Bank AC. Or Phone No.</label><input type="text" name="bank_or_phone" value="{{ old('bank_or_phone', data_get($salaryInfo, 'bank_or_phone')) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Car & Fuel</label><input type="number" step="0.01" name="car_fuel" value="{{ old('car_fuel', data_get($salaryInfo, 'car_fuel')) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Phone & Internet</label><input type="number" step="0.01" name="phone_internet" value="{{ old('phone_internet', data_get($salaryInfo, 'phone_internet')) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Extra Facility</label><input type="number" step="0.01" name="extra_facility" value="{{ old('extra_facility', data_get($salaryInfo, 'extra_facility')) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Tax</label><input type="number" step="0.01" name="tax" value="{{ old('tax', data_get($salaryInfo, 'tax')) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Tax Calculate By</label><select name="tax_calculate_by" class="form-control form-control-sm"><option value="percent" @selected(old('tax_calculate_by', data_get($salaryInfo, 'tax_calculate_by')) === 'percent')>%</option><option value="amount" @selected(old('tax_calculate_by', data_get($salaryInfo, 'tax_calculate_by')) === 'amount')>Amount</option></select></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Date</label><input type="date" name="salary_info_date" value="{{ old('salary_info_date', data_get($salaryInfo, 'salary_info_date')) }}" class="form-control form-control-sm"></div>
    <div class="col-md-6 mb-2"><label class="mb-1">Is Active</label><select name="salary_info_status" class="form-control form-control-sm"><option value="active" @selected(old('salary_info_status', data_get($salaryInfo, 'salary_info_status', 'active')) === 'active')>Active</option><option value="inactive" @selected(old('salary_info_status', data_get($salaryInfo, 'salary_info_status', 'active')) === 'inactive')>Inactive</option></select></div>
</div>